blank_issues_enabled: false
contact_links:
  - name: Contributing Guidelines
    url: https://github.com/charm-ai-labs/Charm/blob/main/CONTRIBUTING.md
    about: Please review this before submitting an issue.
  - name: Get Help
    url: https://discord.gg/gdakynHUEb
    about: Ask questions and chat with the team & community.
  - name: Report a Security Vulnerability
    url: https://github.com/charm-ai-labs/Charm/blob/main/SECURITY.md
    about: Please report vulnerabilities privately instead of opening a public issue.
