name: Trigger Runner Deploy

on:
    push:
        branches:
            - main
        tags:
            - 'v*'
        paths:
            - 'src/**'
            - 'docker/Dockerfile*'

jobs:
    notify-runner:
        runs-on: ubuntu-latest
        steps:
            - name: Trigger Runner Workflow
              uses: peter-evans/repository-dispatch@v3
              with:
                  token: ${{ secrets.SDK_PAT_TOKEN }}
                  repository: charm-ai-labs/charm-cloud-runner
                  event-type: sdk_updated
                  client-payload: '{"ref": "${{ github.ref_name }}"}'
